### ISSUE TITLE
Get the development version of retroharmonize

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/retroharmonize-publication#10]
- [x] Make sure that Rtools and devtools are up and running. 
- [x] You must install Rtools before installing devtools with install.packages("devtools"). 
- [x] Please check that devtools was properly installed
- [x] Your RStudio is connected to github (can be a pain for the first time, help [here](https://happygitwithr.com/rstudio-git-github.html).)
- [x] Please create a for of rOpenGov/retroharmonize to 
[https://github.com/AnnamariaTatrai/retroharmonize](https://github.com/AnnamariaTatrai/)
- [ ] Open it on your local computer as a new project, and do not change anything before we speak.

**Comment by AnnamariaTatrai** [comment]
I think, this is done.
