### ISSUE TITLE
Create an EU SILC subset

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/retroharmonize-publication#8]
- [x] Create a HU and SK subset with at least some of the variables of the [Eurobarometer dataset](https://retroharmonize.dataobservatory.eu/articles/cap.html)
- [x] Add them to your not_included/ directory in the local copy of your forked repository.

**Comment by AnnamariaTatrai** [comment]
A subsample of 100 households (approximately 200 respondents) from each country is selected. The sample datasets are in the not_included folder.

**Comment by AnnamariaTatrai** [comment]
done
