### ISSUE TITLE
Make sure that devtools is installed and works

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/retroharmonize-publication#9]
In order to work with the latest development version of retroharmonize, you need Rtools and devtools installed on your computer. 

` install.packages("devtools")`
`devtools::[install_github](https://devtools.r-lib.org/reference/remote-reexports.html)("rOpenGov/retroharmonize")`

See [retroharmonize README](https://retroharmonize.dataobservatory.eu/)

**Comment by antaldaniel** [comment]
Please leave a note here if you were able to install retroharmonize 0.2.5
@AnnamariaTatrai 
@jrhyse

**Comment by AnnamariaTatrai** [comment]
it works
